django/crud/boards/urls.py
from django.urls import path
from . import views    # 동일한 디렉토리에 있는 views.py 를 import 하겠다.

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:board_pk>/', views.detail, name='detail'),
    path('<int:board_pk>/delete/', views.delete, name='delete'),
    path('<int:board_pk>/edit/', views.edit, name='edit'),
    path('<int:board_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:board_pk>/comments/<int:comment_pk>/edit/', views.comments_edit, name='comments_edit'),
    path('<int:board_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

django/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/crud/boards/models.py
from django.db import models
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Thumbnail

# Start Model T4IR
def board_image_path(instance, filename):
    return f'boards/{instance.pk}번글/images/{filename}'

class Board(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(
        upload_to=board_image_path,
        processors=[Thumbnail(200,300)],
        format='JPEG',
        options={'quality': 90},
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}번 글 - {self.title} : {self.content}'


class Comment(models.Model):
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f'<(Board{self.board_id}: 댓글 {self.id}번째 : {self.content})>'

django/crud/boards/views.py
from django.shortcuts import render, redirect
from .models import Board, Comment


def index(request):
    boards = Board.objects.all()[::-1]
    context = {'boards': boards}
    return render(request, 'boards/index.html', context) # templates 안의 boards 폴더에 있는 index.html을 랜더하겠다.

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        board = Board(title=title, content=content, image=image)
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        return render(request, 'boards/create.html')

def detail(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    comments = board.comment_set.all()

    context = {'board': board, 'comments': comments}
    return render(request, 'boards/detail.html', context)

def delete(request, board_pk):
    if request.method =='POST':
        board = Board.objects.get(pk=board_pk)
        board.delete()
        return redirect('boards:index')
    else:
        return render(request, 'boards/detail.html')

def edit(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        board.title = request.POST.get('title')
        board.content = request.POST.get('content')
        board.image = request.FILES.get('image')
        board.save()
        return redirect('boards:detail', board.pk)
    else:
        context = {'board': board}
        return render(request, 'boards/edit.html', context)

def comments_create(request, board_pk):
    board = Board.objects.get(pk=board_pk)
    if request.method == 'POST':
        comment = Comment()
        # comment.board = board 도 가능하나 정확한 명시가 아니다.
        comment.board_id = board.pk
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board.pk)
    else:
        return redirect('boards:detail', board.pk)

def comments_edit(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST':
        comment.content = request.POST.get('content')
        comment.save()
        return redirect('boards:detail', board_pk)
    else:
        context = {'comment': comment}
        return render(request, 'boards/comment_edit.html', context)

def comments_delete(request, board_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method =='POST':
        comment.content = request.POST.get('content')
        comment.delete()
        return redirect('boards:detail', board_pk)
    else:
        return redirect('boards:detail', board_pk)

django/crud/boards/templates/boards/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!--    <link rel="stylesheet" href="padding.css">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'boards/favicon/favicon.ico' %}" type="image/x-icon">
    <title>CRUD</title>
</head>
<body>
    <img src="{% static 'hulk.png' %}" alt="hulk">
    <div class="'container">
        {% block body %}
        {% endblock %}
    </div>
<!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

django/crud/boards/templates/boards/comment_edit.html
{% extends 'boards/base.html '%}

{% block body %}
<h1 class="text-center">Comment Edit</h1>
<hr>
<form action="{% url 'boards:comments_edit' comment.board.id comment.pk %}" method="POST">
    {% csrf_token %}
    댓글 수정: <input type="text" name="content" value="{{ comment.content }} comment.pk">
    <input type="submit" value="댓글 수정">
</form>

{% endblock %}

django/crud/boards/templates/boards/create.html
{% extends 'boards/base.html' %}

{% block body %}
<br><br><br><br><br>
<p>글이 성공적으로 작성되었습니다.</p>
{% endblock%}

django/crud/boards/templates/boards/detail.html
{% extends "boards/base.html" %}
{% load static %}
{% block body %}
    <h1 class="text-center">DETAIL</h1>
    <h2 class="text-center">{{ board.pk }} 번째 글</h2>
    <hr>
    <p class="text-center">글 제목: {{board.title}}</p>
    <p class="text-center">글 내용: {{board.content}}</p>
    <p class="text-center">글 작성 시각: {{board.created_at}}</p>
    <p class="text-center">글 수정 시각: {{board.updated_at}}</p>
<hr>
    <center>
    <form action="{% url 'boards:comments_create' board.pk %}" method="POST">
        {%csrf_token%}
        <input type="text" name="content" style= width:850px;>
        <input type="submit" value="댓글작성">
    </form>
    </center>
    <center>
    <hr>
        <p><strong>댓글 목록 | 현재 댓글 갯수: {{ comments|length }} 개</strong></p>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
            <a href="{% url 'boards:comments_edit' board.pk comment.pk %}">[댓글 수정]</a><br>
            <form action="{% url 'boards:comments_delete' comment.board.id comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="댓글 삭제">

        {% empty %}
            <p>현재 댓글이 없습니다. </p>
</form>
        {% endfor %}
    </center>
    <hr>
    <center>
        {% if board.image %}
            <h3><b>원본 이미지</b></h3>
            <img src="{{ board.image.url }}" alt="{{ board.image }}">
        {% endif %}
            <p><b>사진이 존재하지 않습니다.</b></p>
    <hr>
    <a href="{% url 'boards:edit' board.pk %}">[글 수정]</a><br>
    <a href="{% url 'boards:index' %}">[메인 페이지]</a><br>


    <form action="{% url 'boards:delete' board.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
        <hr>


    </center>
{% endblock %}

django/crud/boards/templates/boards/edit.html
{% extends 'boards/base.html' %}
{% load static %}
{% block body %}
<br><br>
<h1 class="text-center">EDIT</h1>
<hr>

    {% if board.image %}
        <p><b>기존 이미지</b></p>
        <img src="{{ board.image.url }}" alt="{{ board.image }}">
    {% else %}
        <p><b>기존 이미지가 존재하지 않습니다.</b></p>
    {% endif %}
<hr>
<center>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title">Title</label><br>
        <input type="text" name="title" id="title" value="{{board.title}}" style = width:580px; ><br>
        <label for="content">Content</label><br>
        <textarea name="content" id="content" cols="80" rows="10">{{board.content}}</textarea><br>
        <label for="image">Image</label>
        <input type="file" name="image" id="image" accept="image/*">
        <input type="submit" value="EDIT">
        <a href="{% url 'boards:index' %}">[메인페이지]</a>
    </form>
</center>
{% endblock %}

django/crud/boards/templates/boards/index.html
{% extends 'boards/base.html' %}
{% load static %}
{% block body %}

<h1 class="text-center">INDEX</h1>
<hr>
<img src="{% static 'boards/images/dog.jpg' %}" alt="dog">

<hr>
{% for board in boards %}
    <p class="text-center">글 번호: {{ board.pk }}</p>
    <p class="text-center">글 제목: {{ board.title }}</p>
    <center>
    <a href="{% url 'boards:detail' board.pk %}">[글 상세 보기]</a>
    </center>
    <hr>
{% endfor %}
<center>
    <form action="{% url 'boards:new' %}">
    <input type="submit" value="글쓰기">
    </form>
</center>
{% endblock %}

django/crud/boards/templates/boards/new.html
{% extends 'boards/base.html' %}

{% block body %}
<br><br>
<h1 class="text-center">New</h1>
<hr>
<center>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="title">Title</label><br>
    <input type="text" name="title" id="title" style = width:580px;><br>   <!-- input의 id와 label의 for는 같아야 한다 -->
    <label for="content">Content</label><br>
    <textarea name="content" id="content" cols="80" rows="10"></textarea><br>
    <label for="image">Image</label><br>
    <input type="file" name="image" id="image" accept="image/*">
    <input type="submit" value="Submit">
</form>
<a href="{% url 'boards:index' %}">[메인페이지]</a>
</center>
{% endblock %}