django/prac/movies/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/edit/', views.edit, name='edit'),


]

django/prac/prac/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

django/prac/movies/models.py
from django.db import models

# Create your models here.

class Movie (models.Model):
    title= models.CharField(max_length=100)
    title_origin= models.CharField(max_length=100)
    vote_count= models.IntegerField()
    open_date= models.CharField(max_length=100)
    genre= models.CharField(max_length=100)
    score= models.FloatField()
    poster_url= models.TextField()
    description= models.TextField()

    def __str__(self):
        return f'제목:{self.title} 영화명:{self.title_origin} 투표수:{self.vote_count} ' \
            f'개봉일: {self.open_date} 장르: {self.genre} 점수:{self.score} 포스터:{self.poster_url} 설명: {self.description}'

django/prac/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from django.db import IntegrityError
# Create your views here.
def index(request):
    movies = Movie.objects.all()[::-1]
    context = {'movies': movies}
    return render(request, 'movies/index.html', context)

def new(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        title_origin = request.POST.get('title_origin')
        vote_count = request.POST.get('vote_count')
        open_date = request.POST.get('open_date')
        genre = request.POST.get('genre')
        score = request.POST.get('score')
        poster_url = request.POST.get('poster_url')
        description = request.POST.get('description')
        movie = Movie(title=title,
                      title_origin=title_origin,
                      vote_count=vote_count,
                      open_date=open_date,
                      genre=genre,
                      score=score,
                      poster_url=poster_url,
                      description=description,)
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        return render(request, 'movies/create.html')

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    context = {'movie': movie}
    return render(request, 'movies/detail.html', context)

def delete(request, movie_pk):
    if request.method =='POST':
        movie = Movie.objects.get(pk=movie_pk)
        movie.delete()
        return redirect('movies:index')
    else:
        return render(request, 'movies/detail.html')

def edit(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    if request.method == 'POST':
        movie.title = request.POST.get('title')
        movie.title_origin = request.POST.get('title_origin')
        movie.vote_count = request.POST.get('vote_count')
        movie.open_date = request.POST.get('open_date')
        movie.genre = request.POST.get('genre')
        movie.score = request.POST.get('score')
        movie.poster_url = request.POST.get('poster_url')
        movie.description = request.POST.get('description')
        movie.save()
        return redirect('movies:detail', movie.pk)
    else:
        context = {'movie': movie}
        return render(request, 'movies/edit.html', context)

django/prac/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

django/prac/movies/templates/movies/detail.html
{% extends "movies/base.html" %}
{% load static %}
{% block body %}
<style>
container>div {
        margin: 30px;
        border: 30px solid #008000;
        padding: 30px;
      }
</style>
<center>
    <h1 class="text-center">DETAIL</h1>
    <h2 class="text-center">{{ movie.pk }} 번째 영화</h2>
    <hr>
    <p class="text-center">영화 제목: {{movie.title}}</p>
    <p class="text-center">영화 원 제목: {{movie.title_origin}}</p>
    <p class="text-center">영화 투표 수: {{movie.vote_count}}</p>
    <p class="text-center">영화 개봉일: {{movie.open_date}}</p>
    <p class="text-center">영화 장르: {{movie.genre}}</p>
    <p class="text-center">영화 점수: {{movie.score}}</p>
    <hr>
    <p class="text-center"><<영화 포스터>></p>
    <container>
        <div>
            <img src="{{ movie.poster_url }}" alt="{{movie.title}}">
        </div>
    </container>
    <<영화 줄거리>>
    <container>
        <div>
            <p class="text-center">{{movie.description}}</p>
        </div>
    </container>
    <hr>

    <a href="{% url 'movies:edit' movie.pk %}">[글 수정]</a><br>
    <a href="{% url 'movies:index' %}">[메인 페이지]</a><br>

    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
        {%csrf_token%}
        <input type="submit" value="삭제">
    </form>
</center>
{% endblock %}

django/prac/movies/templates/movies/edit.html
{% extends 'movies/base.html' %}
{% load static %}
{% block body %}
<br><br>
<h1 class="text-center">EDIT</h1>

<center>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="title">타이틀</label>
        <input type="text" id="title" value="{{movie.title}}" name="title"><br>
        <label for="title_origin">본제목</label>
        <input type="text" id="title_origin" value="{{movie.title_origin}}" name="title_origin"><br>
        <label for="vote_count">투표수</label>
        <input type="number" id="vote_count" value="{{movie.vote_count}}" name="vote_count"><br>
        <label for="open_date">개봉일</label>
        <input type="date" id="open_date" value="{{movie.open_date}}" name="open_date"><br>
        <label for="genre">장르</label>
        <input type="text" id="genre" value="{{movie.genre}}" name="genre"><br>
        <label for="score">점수</label>
        <input type="number" min="0" max="10" oninput="validity.valid||(value='');" id="score" value="{{movie.score}}" name="score"><br>
        기존이미지: <br>
        <img src="{{ movie.image.url }}" alt=""><br>
        <img src="{{movie.poster_url}}" alt=""><br>
        <label for="poster_url">포스터 주소</label>
        <input type="text" id="poster_url" value="{{movie.poster_url}}" name="poster_url"><br>
        <label for="image">Image</label>
        <input type="file" name="image" id="image" accept="image/*"><br>
        <label for="description">설명</label>
        <textarea name="description" id="description" cols="30" rows="10">{{movie.description}}</textarea><br>
        <a href="{% url 'movies:index' %}">[메인페이지]</a>
        <input type="submit" value="수정완료">
    </form>
</center>
{% endblock %}

django/prac/movies/templates/movies/index.html
{% extends 'movies/base.html' %}

{% block body %}
<style>
body { margin:0; }
table {
  margin: 5px 0 0;
  border-collapse:collapse;
}
thead {
  position: fixed;
  top: 0;
  background: pink;
}
th {
  border:1px solid silver;
  height: 30px;
}
td { border:1px solid silver; }
th:nth-of-type(1), td:nth-of-type(1) { width:50px; }
th:nth-of-type(2), td:nth-of-type(2) { width:250px; }
th:nth-of-type(3), td:nth-of-type(3) { width:350px; }
th:nth-of-type(4), td:nth-of-type(4) { width:150px; }
th:nth-of-type(5), td:nth-of-type(5) { width:50px; }
th:nth-of-type(6), td:nth-of-type(6) { width:80px; }
tr:nth-child(even) { background: #eee; }
</style>
<center>
    <br><br>
    {%for movie in movies%}
    <table>

        <thead>
            <tr>
                <th>번호</th>
                <th>영화제목</th>
                <th>장르</th>
                <th>개봉일자</th>
                <th>점수</th>
                <th>링크</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{movie.id}}</td>
                <td>{{movie.title}}</td>
                <td>{{movie.genre}}</td>
                <td>{{movie.open_date}}</td>
                <td>{{movie.score}}</td>
                <td><a href="{% url 'movies:detail' movie.pk %}">[상세 보기]</a></td>
            </tr>
        </tbody>
    </table>
    {%endfor%}
    <form action="{% url 'movies:new' %}" method="GET">
        <hr>
    <input type="submit" value="작성하기">
    </form>
</center>
{% endblock %}

django/prac/movies/templates/movies/new.html
{%extends 'movies/base.html'%}
{%block body%}
<form action="" method="POST">
    {%csrf_token%}
    <label for="title">타이틀</label>
    <input type="text" id="title" name="title"><br>
    <label for="title_origin">본제목</label>
    <input type="text" id="title_origin" name="title_origin"><br>
    <label for="vote_count">투표수</label>
    <input type="number" id="vote_count" name="vote_count"><br>
    <label for="open_date">개봉일</label>
    <input type="date" id="open_date" name="open_date"><br>
    <label for="genre">장르</label>
    <input type="text" id="genre" name="genre"><br>
    <label for="score">점수</label>
    <input type="number" min="0" oninput="validity.valid||(value='');" step="0.5" id="score" name="score"><br>
    <label for="poster_url">포스터 주소</label>
    <input type="text" id="poster_url" name="poster_url"><br>
    <label for="description">설명</label>
    <textarea name="description" id="description" cols="30" rows="10"></textarea><br>
    <input type="submit" value="작성하기">
</form>
<a href="{% url 'movies:index' %}">돌아가기</a>
{%endblock%}